services:
  - type: web
    name: financial-news-app
    env: node
    buildCommand: |
      cd client && npm install --include=dev && npm cache clean --force && npm run build

    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: financial-news-db
          property: connectionString
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  - name: financial-news-db
    plan: free
    region: virginia  # Choose your preferred region
