services:
  - type: web
    name: financial-news-app
    runtime: node
    plan: free
    buildCommand: |
      npm install
      cd server && npm install
      cd ../client && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: financial-news-db
          property: connectionString
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: financial-news-db
    plan: free
    region: virginia  # Choose your preferred region
