services:
  - type: web
    name: financial-news-app
    runtime: node
    buildCommand: cd client && npm install --force && npm install tailwindcss@latest postcss@latest autoprefixer@latest && npm run build --mode production && cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: NODE_VERSION
        value: 18.17.0
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
    plan: free

databases:
  - name: financial-news-db
    databaseName: financial_news
    user: financial_news_user
    plan: free 
