services:
  - type: web
    name: financial-news-app
    runtime: node
    buildCommand: |
      cd client && npm install --production=false && npm run build -- --mode production
      cd ../server && npm install --production=false
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: financial-news-db
          property: connectionString
    plan: free

databases:
  - name: financial-news-db
    databaseName: financial_news
    user: financial_news_user
    plan: free 